CREATE SEQUENCE CATECODE_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 5000 NOCYCLE;

CREATE SEQUENCE VALUECODE_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 5000 NOCYCLE;

CREATE SEQUENCE MENU_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 5000 NOCYCLE;
  

CREATE SEQUENCE RESTAURANT_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 5000 NOCYCLE;

CREATE SEQUENCE RESTCATECODE_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 5000 NOCYCLE;

CREATE SEQUENCE MENU2RESTAURANT_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 999999 NOCYCLE;


CREATE SEQUENCE MENUDATA_SEQ
  START WITH 1
  INCREMENT BY 1 MAXVALUE 999999 NOCYCLE;


INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '어울리는날씨');
INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '식당분류');
INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '메뉴분류');
INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '특별한날');
INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '컨디션');
INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '거리');
INSERT INTO CATECODE (CATE_ID, NAME) VALUES (CATECODE_SEQ.NEXTVAL, '주관적특징');

INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '비오는날');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '눈오는날');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '더운날');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '추운날');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '맑은날');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '복날');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '해장필요');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '보양식');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '가까운데');
INSERT INTO VALUECODE (VALUE_ID, VALUE) VALUES (VALUECODE_SEQ.NEXTVAL, '아무데나');

SELECT * FROM VALUECODE;

INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '구내식당밥');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '김치찌개');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '된장찌개');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '청국장');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '칼국수');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '냉면');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '라멘');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '삼겹살');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '쪽갈비');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '닭갈비');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '육개장');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '돈까스');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '커리');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '부대찌개');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '짜장면');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '짬뽕');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '탕수육');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '석갈비');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '햄버거');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '파전');
INSERT INTO MENU (ID, NAME) VALUES (MENU_SEQ.NEXTVAL, '치킨');


INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '구내식당');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '고기집');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '횟집');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '중국집');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '한식집');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '김밥천국');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '이탈리안레스토랑');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '인도음식점');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '일식집');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '돈까스집');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '짬뽕전문점');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '패스트푸드');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '패밀리레스토랑');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '일반식당');
INSERT INTO RESTCATECODE (ID, NAME) VALUES (RESTCATECODE_SEQ.NEXTVAL, '치킨집');

SELECT * FROM RESTCATECODE;

INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '해수연', '', '', 1);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '우진식당', '', '', 1);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '한빛식당', '', '', 1);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '우리푸드', '', '', 1);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '리원', '', '', 4);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '인디(Indy)', '', '', 8);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '이비가짬뽕', '', '', 11);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '병규돈까스', '', '', 10);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '버거킹', '', '', 12);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '써브웨이', '', '', 12);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '강호동치킨', '', '', 15);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '다사랑', '', '', 15);
/* 구내식당 제외한 모든 음식점은 일반 음식점에도 포함 */

INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '5.5닭갈비', '', '', 14);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '청주본가(구 배불뚝집)', '', '', 14);
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '띠울', '', '', 14);


SELECT * FROM RESTAURANT;

SELECT * FROM MENU;

/*
1	해수연			1
2	우진식당			1
3	한빛식당			1
4	우리푸드			1
5	리원			4
6	인디(Indy)			8
7	써브웨이			12
8	버거킹			12
9	이비가짬뽕			11
10	병규돈까스			10
11	5.5닭갈비			14
12	청주본가(구 배불뚝집)			14
13	띠울			14
*/
/* 구내식당 매핑 */
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 1, 1);
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 1, 2);
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 1, 3);
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 1, 4);

/* 나머지 */
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 12, 10); -- 돈까스 - 병규돈가스
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 13, 8); -- 커리 - 인디
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 10, 11); -- 닭갈비 - 5.5

INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 15, 5); -- 탕수육 - 리원
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 16, 5); -- 짜장면 - 리원
INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 17, 5); -- 짬뽕 - 리원

INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 17, 11); -- 짬뽕 - 이비가

INSERT INTO MENU2RESTAURANT (ID, MENU_ID, RESTAURANT_ID) VALUES (MENU2RESTAURANT_SEQ.NEXTVAL, 19, 12); -- 햄버거 - 버거킹


SELECT * FROM MENU;

SELECT * FROM CATECODE; 
/*
1	특별한날
2	어울리는날씨
3	식당분류
4	메뉴분류
5	컨디션
6	거리
7	주관적특징
*/

SELECT * FROM VALUECODE;
/*
1	비오는날
2	눈오는날
3	더운날
4	추운날
5	맑은날
6	가까운데
7	아무데나
8	복날
9	해장필요
10 보양식
*/
-- 거리
INSERT INTO MENUDATA (ID, MENU_ID, CATE_ID, VALUE_ID) VALUES (MENUDATA_SEQ.NEXTVAL, 1, 6, 6); -- 거리가(6) 가까운(3) 구내식당밥(1)

-- 날씨
INSERT INTO MENUDATA (ID, MENU_ID, CATE_ID, VALUE_ID) VALUES (MENUDATA_SEQ.NEXTVAL, 6, 2, 3);   -- 날씨가(2) 더운날(3) 냉면(6)
INSERT INTO MENUDATA (ID, MENU_ID, CATE_ID, VALUE_ID) VALUES (MENUDATA_SEQ.NEXTVAL, 20, 2, 1);  -- 날씨가(2) 비오는날(1) 파전(20)

-- 컨디션
INSERT INTO MENUDATA (ID, MENU_ID, CATE_ID, VALUE_ID) VALUES (MENUDATA_SEQ.NEXTVAL, 17, 5, 9);

SELECT * FROM MENUDATA D, VALUECODE VAL,
              CATECODE CATE, MENU M, MENU2RESTAURANT M2R, RESTAURANT R
WHERE D.VALUE_ID = VAL.VALUE_ID
AND D.CATE_ID = CATE.CATE_ID
AND D.MENU_ID = M.ID
AND M.ID = M2R.MENU_ID
AND M2R.RESTAURANT_ID = R.ID
;

SELECT * FROM RESTAURANT
WHERE ID IN (
SELECT * FROM MENU2RESTAURANT M2R , MENU M
WHERE M2R.MENU_ID = M.ID
)
;

-- 11
DELETE FROM MENU2RESTAURANT
WHERE ID = 21;

UPDATE MENU2RESTAURANT
SET MENU_ID = 10
WHERE ID = 21
;

commit;

		SELECT 
			r.id as id,
			r.name as name,
			r.addr as addr,
			r.contact as contact,
			(select name from restcatecode where id = r.cate_id) cateName
		FROM 
			restaurant r,
			restcatecode rcate
		WHERE
			r.cate_id = rcate.id
		AND rcate.id = 1;
    
    
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '200','thunderstorm with light rain','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '201','thunderstorm with rain  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '202','thunderstorm with heavy rain  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '210','light thunderstorm  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '211','thunderstorm  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '212','heavy thunderstorm  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '221','ragged thunderstorm  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '230','thunderstorm with light drizzle  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '231','thunderstorm with drizzle  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '232','thunderstorm with heavy drizzle  ','11d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '300','light intensity drizzle  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '301','drizzle  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '302','heavy intensity drizzle  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '310','light intensity drizzle rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '311','drizzle rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '312','heavy intensity drizzle rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '313','shower rain and drizzle  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '314','heavy shower rain and drizzle  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '321','shower drizzle  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '500','light rain  ','10d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '501','moderate rain  ','10d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '502','heavy intensity rain  ','10d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '503','very heavy rain  ','10d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '504','extreme rain  ','10d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '511','freezing rain  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '520','light intensity shower rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '521','shower rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '522','heavy intensity shower rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '531','ragged shower rain  ','09d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '600','light snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '601','snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '602','heavy snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '611','sleet  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '612','shower sleet  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '615','light rain and snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '616','rain and snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '620','light shower snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '621','shower snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '622','heavy shower snow  ','13d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '701','mist  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '711','smoke  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '721','haze  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '731','sand, dust whirls  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '741','fog  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '751','sand  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '761','dust  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '762','volcanic ash  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '771','squalls  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '781','tornado  ','50d.png');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '800','clear sky  ','01d.png ');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '801','few clouds  ','02d.png ');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '802','scattered clouds  ','03d.png ');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '803','broken clouds  ','04d.png ');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '804','overcast clouds  ','04d.png ');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '900','tornado','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '901','tropical storm','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '902','hurricane','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '903','cold','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '904','hot','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '905','windy','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '906','hail','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '951','calm','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '952','light breeze','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '953','gentle breeze','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '954','moderate breeze','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '955','fresh breeze','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '956','strong breeze','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '957','high wind, near gale','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '958','gale','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '959','severe gale','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '960','storm','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '961','violent storm','');
INSERT INTO WEATHERCODE ( ID, CODE, NAME, IMG ) VALUES ( WEATHERCODE_SEQ.NEXTVAL, '962','hurricane','');

 update valuecode
set ref_cate_id = 2
where value_id in (1,2,3,4,5)
;

update valuecode
set ref_cate_id = 6
where value_id in (6,7)
;

update valuecode
set ref_cate_id = 1
where value_id in (8)
;

update valuecode
set ref_cate_id = 5
where value_id in ( 9, 10)
;
/*
1	특별한날
2	어울리는날씨
3	식당분류
4	메뉴분류
5	컨디션
6	거리
7	주관적특징
*/
SELECT * FROM VALUECODE;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '패스트푸드', 4)     -- 메뉴분류 : 패스트푸드 
;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '일식', 4)     -- 메뉴분류 : 일식
;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '중화요리', 4)     -- 메뉴분류 : 중화요리
;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '한식', 4)     -- 메뉴분류 : 한식
;
INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '양식', 4)     -- 메뉴분류 : 양식
;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '패밀리레스토랑', 3)     -- 메뉴분류 : 중화요리
;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '뷔페', 3)     -- 메뉴분류 : 중화요리
;

INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '횟집', 3)     -- 메뉴분류 : 중화요리
;

ROLLBACK;

SELECT * FROM VALUECODE;

COMMIT;


INSERT INTO VALUECODE
(VALUE_ID, VALUE, REF_CATE_ID)
VALUES
(VALUECODE_SEQ.NEXTVAL, '블랙데이', 1)     -- 메뉴분류 : 중화요리
;

SELECT * FROM MENU;
/*
1	구내식당밥
2	김치찌개
3	된장찌개
4	청국장
5	칼국수
6	냉면
7	라멘
8	삼겹살
9	쪽갈비
10	닭갈비
11	육개장
12	돈까스
13	커리
14	부대찌개
15	탕수육
16	짜장면
17	짬뽕
18	석갈비
19	햄버거
20	파전
21	치킨
*/
SELECT * FROM MENUDATA
;
/*
  M C V
1	1	6	6     구내식당밥 - 거리 - 가까운데
3	6	2	3     된장찌개  - 어울리는날씨 - 더운날(?)
4	20	2	1   파전    -  어울리는날씨 - 비오는요
5	17	5	9   짬뽕    -  컨디션    - 해장필요

1	비오는날	2
2	눈오는날	2
3	더운날	2
4	추운날	2
5	맑은날	2
6	가까운데	6
7	아무데나	6
8	복날	1
9	해장필요	5
10	보양식	5
21	패스트푸드	4
22	일식	4
23	중화요리	4
24	한식	4
25	양식	4
29	패밀리레스토랑	3
30	뷔페	3
31	횟집	3
32	블랙데이	1
*/
SELECT * FROM CATECODE;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 1, 6, 7)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 2, 6, 7)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 5, 2, 1)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 6, 2, 3)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 7, 2, 1)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 12, 3, 21)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 15, 3, 23)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 16, 3, 23)
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 17, 3, 23)
;


INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 19, 3, 21)
;


INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 15, 3, 23)
;

COMMIT;



INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,200); -- Thunderstorm
INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,300); -- Drizzle
INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,500); -- Rain
INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,600); -- Snow
INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,700); -- Atmosphere
INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,800); -- Clouds
INSERT INTO valueCODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,900); -- Extreme & Additional


select * from restcatecode;
select * from restaurant;

INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '우에무라', '대전 유성구 관평동 986', '042-933-1119', 9); -- 일식집 우에무라
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '풍전삼계탕', '대전 유성구 관평동 1181', '042-483-0060', 34); -- 일반식당 풍전삼계탕
INSERT INTO RESTAURANT (ID, NAME, ADDR, CONTACT, CATE_ID) VALUES (RESTAURANT_SEQ.NEXTVAL, '최가네영양탕삼계탕', '대전 유성구 관평동 1204', '042-935-0029', 34); -- 일반식당 최가네영양탕삼계탕


INSERT INTO MENU2RESTAURANT
(ID,MENU_ID, RESTAURANT_ID)
VALUES
(MENU2RESTAURANT_SEQ.NEXTVAL, 7, 61); -- 라멘 -우에무라 

INSERT INTO MENU2RESTAURANT
(ID,MENU_ID, RESTAURANT_ID)
VALUES
(MENU2RESTAURANT_SEQ.NEXTVAL, 43, 62); -- 삼계탕 - 풍전삼계탕


INSERT INTO MENU2RESTAURANT
(ID,MENU_ID, RESTAURANT_ID)
VALUES
(MENU2RESTAURANT_SEQ.NEXTVAL, 43, 64); -- 삼계탕 - 최가네영양탕삼계탕



select * from menu;
select * from catecode;
select * from valuecode;
select * from menudata
where menu_id = 7
;

update menudata
set cate_id = 2
where menu_id = 7
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 7, 2, 51)
;  -- 라멘 어울리는날씨 비오는날

INSERT INTO MENU
(ID, NAME)
VALUES
(MENU_SEQ.NEXTVAL, '냉소바')
;

INSERT INTO MENU
(ID, NAME)
VALUES
(MENU_SEQ.NEXTVAL, '콩국수')
;

INSERT INTO MENU
(ID, NAME)
VALUES
(MENU_SEQ.NEXTVAL, '삼계탕')
;


COMMIT;

INSERT INTO VALUECODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,'초복'); 
INSERT INTO VALUECODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,'중복'); 
INSERT INTO VALUECODE ( value_id, value) VALUES ( VALUECODE_SEQ.NEXTVAL,'말복'); 

SELECT * FROM VALUECODE;

SELECT * FROM MENUDATA
where menu_id = 7
;

INSERT INTO MENUDATA
(ID,MENU_ID, CATE_ID, VALUE_ID)
VALUES 
(MENUDATA_SEQ.NEXTVAL, 43, 1, 63)
; -- 삼계탕 특별한날 초복



COMMIT;

